In [42]:
import pandas as pd

In [43]:
bal = pd.read_excel('bal_2025.xlsx')

In [44]:
df_bal = pd.DataFrame(bal)

In [45]:
df_bal.columns

Index(['СПИСЪК НА ПАРАЛЕЛКИТЕ С ДЪРЖАВЕН ПЛАН-ПРИЕМ В VIII КЛАС ЗА УЧЕБНАТА 2025/2026 ГОДИНА В ОБЛАСТ СОФИЯ-ГРАД \nс кодове и балообразуване',
       'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5',
       'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10',
       'Unnamed: 11'],
      dtype='str')

In [46]:
df_bal.rename(columns={'Unnamed: 2':'School name'}, inplace=True)

In [47]:
df_bal.rename(columns={'Unnamed: 3':'Field code'}, inplace=True)

In [48]:
df_bal.rename(columns={'Unnamed: 4':'Field name'}, inplace=True)

In [49]:
df_bal.rename(columns={'Unnamed: 6':'Formula'}, inplace=True)

In [50]:
df_bal

,СПИСЪК НА ПАРАЛЕЛКИТЕ С ДЪРЖАВЕН ПЛАН-ПРИЕМ В VIII КЛАС ЗА УЧЕБНАТА 2025/2026 ГОДИНА В ОБЛАСТ СОФИЯ-ГРАД \nс кодове и балообразуване,Unnamed: 1,School name,Field code,Field name,Unnamed: 5,Formula,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11
0,№,РАЙОН,Училище - име,Код на паралелката,Паралелка - име,Вид на паралелката,Балообразуване,Форма на обучение,Брой паралелки,Общо основание,Мъже,Жени
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1,БАНКЯ,"78. Средно училище ""Христо Смирненски"", ГР.БАНКЯ",463,Извършване на термални процедури - АЕ,професионална,(2 * БЕЛ + 2 * МАТ) + (1 * БЗО + 1 * ХООС),дневна,1,26,0,0
3,2,БАНКЯ,"78. Средно училище ""Христо Смирненски"", ГР.БАНКЯ",4798,"Софтуерни и хардуерни науки - АЕ интензивно, НЕ",профилирана,(2 * БЕЛ + 2 * МАТ) + (1 * М + 1 * КМИТ),дневна,1,26,0,0
4,3,БАНКЯ,"Професионална гимназия по туризъм ""Алеко Конс...",344,Организация на хотелиерството - АЕ,професионална,(2 * БЕЛ + 2 * МАТ) + (1 * ИЦ + 1 * ГИ),дневна,1,26,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
388,387,ТРИАДИЦА,"НАЦИОНАЛНА ТЪРГОВСКО - БАНКОВА ГИМНАЗИЯ, ГР.СОФИЯ",941,"Електронна търговия - РЕ интензивно, АЕ",професионална,(2 * БЕЛ + 2 * МАТ) + (1 * БЕЛ + 1 * М),дневна,1,0,13,13
389,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,410,NaN,NaN,NaN
390,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
391,"Забележка: Балообразуването се формира, както ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
392,"Изключение са паралелките, за които се балообр...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [51]:
df_bal.columns

Index(['СПИСЪК НА ПАРАЛЕЛКИТЕ С ДЪРЖАВЕН ПЛАН-ПРИЕМ В VIII КЛАС ЗА УЧЕБНАТА 2025/2026 ГОДИНА В ОБЛАСТ СОФИЯ-ГРАД \nс кодове и балообразуване',
       'Unnamed: 1', 'School name', 'Field code', 'Field name', 'Unnamed: 5',
       'Formula', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10',
       'Unnamed: 11'],
      dtype='str')

In [54]:
df_bal['Formula']

0                                  Балообразуване
1                                             NaN
2      (2 * БЕЛ + 2 * МАТ) + (1 * БЗО + 1 * ХООС)
3        (2 * БЕЛ + 2 * МАТ) + (1 * М + 1 * КМИТ)
4         (2 * БЕЛ + 2 * МАТ) + (1 * ИЦ + 1 * ГИ)
                          ...
388       (2 * БЕЛ + 2 * МАТ) + (1 * БЕЛ + 1 * М)
389                                           NaN
390                                           NaN
391                                           NaN
392                                           NaN
Name: Formula, Length: 393, dtype: str

In [55]:
df_bal.columns

Index(['СПИСЪК НА ПАРАЛЕЛКИТЕ С ДЪРЖАВЕН ПЛАН-ПРИЕМ В VIII КЛАС ЗА УЧЕБНАТА 2025/2026 ГОДИНА В ОБЛАСТ СОФИЯ-ГРАД \nс кодове и балообразуване',
       'Unnamed: 1', 'School name', 'Field code', 'Field name', 'Unnamed: 5',
       'Formula', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10',
       'Unnamed: 11'],
      dtype='str')

In [57]:
new_frame = pd.DataFrame()

In [58]:
new_frame['1'] = df_bal['School name']
new_frame['2'] = df_bal['Field code']
new_frame['3'] = df_bal['Field name']
new_frame['4'] = df_bal['Formula']

In [59]:
new_frame

,1,2,3,4
0,Училище - име,Код на паралелката,Паралелка - име,Балообразуване
1,NaN,NaN,NaN,NaN
2,"78. Средно училище ""Христо Смирненски"", ГР.БАНКЯ",463,Извършване на термални процедури - АЕ,(2 * БЕЛ + 2 * МАТ) + (1 * БЗО + 1 * ХООС)
3,"78. Средно училище ""Христо Смирненски"", ГР.БАНКЯ",4798,"Софтуерни и хардуерни науки - АЕ интензивно, НЕ",(2 * БЕЛ + 2 * МАТ) + (1 * М + 1 * КМИТ)
4,"Професионална гимназия по туризъм ""Алеко Конс...",344,Организация на хотелиерството - АЕ,(2 * БЕЛ + 2 * МАТ) + (1 * ИЦ + 1 * ГИ)
...,...,...,...,...
388,"НАЦИОНАЛНА ТЪРГОВСКО - БАНКОВА ГИМНАЗИЯ, ГР.СОФИЯ",941,"Електронна търговия - РЕ интензивно, АЕ",(2 * БЕЛ + 2 * МАТ) + (1 * БЕЛ + 1 * М)
389,NaN,NaN,NaN,NaN
390,NaN,NaN,NaN,NaN
391,NaN,NaN,NaN,NaN
392,NaN,NaN,NaN,NaN

In [60]:
new_frame['4']

0                                  Балообразуване
1                                             NaN
2      (2 * БЕЛ + 2 * МАТ) + (1 * БЗО + 1 * ХООС)
3        (2 * БЕЛ + 2 * МАТ) + (1 * М + 1 * КМИТ)
4         (2 * БЕЛ + 2 * МАТ) + (1 * ИЦ + 1 * ГИ)
                          ...
388       (2 * БЕЛ + 2 * МАТ) + (1 * БЕЛ + 1 * М)
389                                           NaN
390                                           NaN
391                                           NaN
392                                           NaN
Name: 4, Length: 393, dtype: str